- src: git+ssh://git@git.arkena.net/ansible.galaxy/add-debian-repo
  name: add-debian-repo

- src: HanXHX.redis

- src: git+ssh://git@git.arkena.net/ansible.galaxy/postgresql-debian
  name: postgresql-debian

- src: git+ssh://git@git.arkena.net/ansible.galaxy/stratus-debian
  name: stratus-debian

- src: git+ssh://git@git.arkena.net/ansible.galaxy/stratus-pg-migrate
  name: stratus-pg-migrate

- src: git+ssh://git@git.arkena.net/ansible.galaxy/ferm-common-debian
  name: ferm-common-debian
