
- name: "Prepare infra for stratus (1/2)"
  hosts: stratus_db
  roles:
    - role: postgresql-debian
    - role: HanXHX.redis

- name: "Install stratus"
  hosts: stratus_worker
  roles:
    - role: add-debian-repo
      repo: 'deb http://debian.arkena.net/arkena-dev/ stretch main'
      key_url: 'http://debian.arkena.net/arkena-dev/key.gpg'

    - role: stratus-debian

- name: "Open port in firewall"
  hosts: stratus_db:stratus_worker
  roles:
    - role: ferm-common-debian

- name: "Make db migration"
  hosts: stratus_worker
  vars:
    stratus_db_group: 'stratus_db'
    stratus_pg_password: 'pipo'
  roles:
    - role: stratus-pg-migrate
